work = str(input('Digite uma palavra: '))
print('O tipo primitivo desse valor é {}'.format(type(work)))
print('Só tem espaços?: {}'.format(work.isspace()))
print('É um numero?: {}'.format(work.isnumeric()))
print('É alfabético?: {}'.format(work.isalpha()))
print('É alfanumerico?: {}'.format(work.isalnum()))
print('Esta capitalizado?: {}'.format(work.istitle()))
print('Está em letras minusculas?: {}'.format(work.islower()))
print('Esta em caixa alta?: {}'.format(work.isupper()))
